CREATE DATABASE SocialMediaPlatform;
USE SocialMediaPlatform;

CREATE TABLE Users (
	UserID INT IDENTITY PRIMARY KEY,
	UserName NVARCHAR(100) NOT NULL, 
	Gender NVARCHAR(10) CHECK (Gender IN ('female', 'male')) NOT NULL,
	DOB DATE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	JoinDate DATETIME DEFAULT GETUTCDATE() NOT NULL
);

CREATE TABLE Post (
	PostID INT IDENTITY PRIMARY KEY,
	Content NVARCHAR(MAX) NOT NULL,
	PostDate DATETIME DEFAULT GETUTCDATE() NOT NULL,
	Visibility VARCHAR(20) 
				CHECK (Visibility IN ('Public', 'Private'))
				DEFAULT 'Private' 
				NOT NULL,
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Comment (
	CommentID INT IDENTITY PRIMARY KEY,
	Content VARCHAR(MAX) NOT NULL,
	CommentDate DATETIME DEFAULT GETUTCDATE() NOT NULL,
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	PostID INT NOT NULL,
	FOREIGN KEY (PostID) REFERENCES Post(PostID)
);

CREATE TABLE Interaction (
	InteractionID INT IDENTITY PRIMARY KEY,
	Type VARCHAR(100),
	InteractionDate DATETIME DEFAULT GETUTCDATE() NOT NULL,
	UserID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	PostID INT NOT NULL,
	FOREIGN KEY (PostID) REFERENCES Post(PostID)
);

CREATE TABLE User_Post (
	UserID INT NOT NULL,
	PostID INT NOT NULL,
	PRIMARY KEY (UserID, PostID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	FOREIGN KEY (PostID) REFERENCES Post(PostID)
);